"use strict";(self.webpackChunkrc_util=self.webpackChunkrc_util||[]).push([[558],{94398:function(A,f,e){e.r(f);var g=e(71100),p=e(35532),M=e(37402),P=e(38707),y=e(75208),D=e(67915),C=e(37134),s=e(27544),h=e(67294),t=e(85893);function a(){var l=(0,s.eL)(),E=l.texts;return(0,t.jsx)(s.dY,{children:(0,t.jsx)(t.Fragment,{children:(0,t.jsx)(s.Dl,{demo:{id:"docs-demo-dynaymic-css-demo-dynaymiccss"},previewerProps:{iframe:!0,filename:"docs/examples/dynaymicCSS.tsx"}})})})}f.default=a},33126:function(A,f,e){e.d(f,{zX:function(){return g.Z}});var g=e(43194),p=e(28282),M=e(59364),P=e(52677),y=e(97857),D=e(19632),C=e(61227);function s(n,u,r,o){if(!u.length)return r;var v=_toArray(u),m=v[0],i=v.slice(1),d;return!n&&typeof m=="number"?d=[]:Array.isArray(n)?d=_toConsumableArray(n):d=_objectSpread({},n),o&&r===void 0&&i.length===1?delete d[m][i[0]]:d[m]=s(d[m],i,r,o),d}function h(n,u,r){var o=arguments.length>3&&arguments[3]!==void 0?arguments[3]:!1;return u.length&&o&&r===void 0&&!get(n,u.slice(0,-1))?n:s(n,u,r,o)}function t(n){return _typeof(n)==="object"&&n!==null&&Object.getPrototypeOf(n)===Object.prototype}function a(n){return Array.isArray(n)?[]:{}}var l=typeof Reflect=="undefined"?Object.keys:Reflect.ownKeys;function E(){for(var n=arguments.length,u=new Array(n),r=0;r<n;r++)u[r]=arguments[r];var o=a(u[0]);return u.forEach(function(v){function m(i,d){var O=new Set(d),c=get(v,i),S=Array.isArray(c);if(S||t(c)){if(!O.has(c)){O.add(c);var T=get(o,i);S?o=h(o,i,[]):(!T||_typeof(T)!=="object")&&(o=h(o,i,a(c))),l(c).forEach(function(j){m([].concat(_toConsumableArray(i),[j]),O)})}}else o=h(o,i,c)}m([])}),o}var _=e(16144)},92718:function(A,f,e){e.d(f,{Z:function(){return h}});var g=e(97857),p=e.n(g),M=`accept acceptCharset accessKey action allowFullScreen allowTransparency
    alt async autoComplete autoFocus autoPlay capture cellPadding cellSpacing challenge
    charSet checked classID className colSpan cols content contentEditable contextMenu
    controls coords crossOrigin data dateTime default defer dir disabled download draggable
    encType form formAction formEncType formMethod formNoValidate formTarget frameBorder
    headers height hidden high href hrefLang htmlFor httpEquiv icon id inputMode integrity
    is keyParams keyType kind label lang list loop low manifest marginHeight marginWidth max maxLength media
    mediaGroup method min minLength multiple muted name noValidate nonce open
    optimum pattern placeholder poster preload radioGroup readOnly rel required
    reversed role rowSpan rows sandbox scope scoped scrolling seamless selected
    shape size sizes span spellCheck src srcDoc srcLang srcSet start step style
    summary tabIndex target title type useMap value width wmode wrap`,P=`onCopy onCut onPaste onCompositionEnd onCompositionStart onCompositionUpdate onKeyDown
    onKeyPress onKeyUp onFocus onBlur onChange onInput onSubmit onClick onContextMenu onDoubleClick
    onDrag onDragEnd onDragEnter onDragExit onDragLeave onDragOver onDragStart onDrop onMouseDown
    onMouseEnter onMouseLeave onMouseMove onMouseOut onMouseOver onMouseUp onSelect onTouchCancel
    onTouchEnd onTouchMove onTouchStart onScroll onWheel onAbort onCanPlay onCanPlayThrough
    onDurationChange onEmptied onEncrypted onEnded onError onLoadedData onLoadedMetadata
    onLoadStart onPause onPlay onPlaying onProgress onRateChange onSeeked onSeeking onStalled onSuspend onTimeUpdate onVolumeChange onWaiting onLoad onError`,y="".concat(M," ").concat(P).split(/[\s\n]+/),D="aria-",C="data-";function s(t,a){return t.indexOf(a)===0}function h(t){var a=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1,l;a===!1?l={aria:!0,data:!0,attr:!0}:a===!0?l={aria:!0}:l=p()({},a);var E={};return Object.keys(t).forEach(function(_){(l.aria&&(_==="role"||s(_,D))||l.data&&s(_,C)||l.attr&&y.includes(_))&&(E[_]=t[_])}),E}}}]);
